# Generated by Django 4.1.6 on 2023-03-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlibustaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Last name')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='Nickname')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail')),
                ('homepage', models.CharField(blank=True, default='', max_length=255, verbose_name='First name')),
                ('main_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='different_names', to='third_part_libraries.flibustaauthor', verbose_name='Main author')),
            ],
        ),
    ]
