# Generated by Django 4.1.7 on 2023-04-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('third_part_libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flibustaauthor',
            name='library_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_authors', to='library.author', verbose_name='Linked library author'),
        ),
        migrations.AlterField(
            model_name='flibustaauthor',
            name='homepage',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Homepage'),
        ),
    ]
