# Generated by Django 4.1.7 on 2023-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_part_libraries', '0002_flibustaauthor_library_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlibustaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_code', models.CharField(max_length=100, unique=True, verbose_name='Genre code')),
                ('genre_desc', models.CharField(max_length=200, verbose_name='Genre description')),
                ('genre_meta', models.CharField(max_length=100, verbose_name='Genre meta')),
            ],
        ),
    ]
