services:
#  web:
#    build: .
#    image: leechlab/bookshelf:latest
#    depends_on:
#      db:
#        condition: service_healthy
#    healthcheck:
#      test: curl -f http://localhost:80/ping/ || exit 1
#      interval: 60s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
#    working_dir: /Bookshelf
#    env_file:
#      - .env
#    environment:
#      - PG_DATABASE_ADDRESS=db
#      - IS_DOCKER=true
#      - FILL_DATABASE=${FILL_DATABASE}
#    volumes:
#      - "staticfiles:/Bookshelf/bookshelf/static"
#    ports:
#      - "8083:80"
#    networks:
#      - front-tier
#      - back-tier
#    restart: "unless-stopped"

  db:
    build: postgres
    image:  leechlab/bookshelf-db:latest
    env_file:
      - .env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: bash /healthchecks/postgres.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    ports:
      - "32768:5432"
    networks:
      - back-tier
    restart: "unless-stopped"

volumes:
  staticfiles:
  db-data:

networks:
  front-tier:
  back-tier:
