# Generated by Django 5.2.5 on 2025-08-31 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlibustaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_code', models.CharField(max_length=100, unique=True, verbose_name='Genre code')),
                ('genre_desc', models.CharField(max_length=200, verbose_name='Genre description')),
                ('genre_meta', models.CharField(max_length=100, verbose_name='Genre meta')),
            ],
        ),
        migrations.CreateModel(
            name='FlibustaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Last name')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='Nickname')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail')),
                ('homepage', models.CharField(blank=True, default='', max_length=255, verbose_name='Homepage')),
                ('library_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_authors', to='library.author', verbose_name='Linked library author')),
                ('main_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='different_names', to='third_party_libraries.flibustaauthor', verbose_name='Main author')),
            ],
        ),
    ]
