# Generated by Django 6.0.2 on 2026-03-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlibustaAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=99, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=99, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=99, verbose_name='Last Name')),
                ('nickname', models.CharField(blank=True, default='', max_length=33, verbose_name='Nickname')),
                ('uid', models.IntegerField(db_index=True, default=0, verbose_name='User ID')),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Email')),
                ('homepage', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Homepage')),
                ('gender', models.CharField(blank=True, default='', max_length=1, verbose_name='Gender')),
                ('master_id', models.IntegerField(db_index=True, default=0, verbose_name='Master ID')),
            ],
            options={
                'verbose_name': 'Flibusta Author',
                'verbose_name_plural': 'Flibusta Authors',
            },
        ),
        migrations.CreateModel(
            name='FlibustaBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.PositiveIntegerField(db_index=True, default=0, verbose_name='File Size')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=254, verbose_name='Title')),
                ('title1', models.CharField(blank=True, db_index=True, default='', max_length=254, verbose_name='Title (Alt)')),
                ('lang', models.CharField(blank=True, db_index=True, default='ru', max_length=3, verbose_name='Language')),
                ('lang_ex', models.PositiveSmallIntegerField(default=0, verbose_name='Language Extended')),
                ('src_lang', models.CharField(blank=True, default='', max_length=3, verbose_name='Source Language')),
                ('file_type', models.CharField(blank=True, db_index=True, default='', max_length=4, verbose_name='File Type')),
                ('encoding', models.CharField(blank=True, default='', max_length=32, verbose_name='Encoding')),
                ('year', models.SmallIntegerField(db_index=True, default=0, verbose_name='Year')),
                ('deleted', models.CharField(db_index=True, default='0', max_length=1, verbose_name='Deleted')),
                ('ver', models.CharField(blank=True, default='', max_length=8, verbose_name='Version')),
                ('file_author', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='File Author')),
                ('n', models.PositiveIntegerField(db_index=True, default=0, verbose_name='N')),
                ('keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='Keywords')),
                ('md5', models.CharField(max_length=32, unique=True, verbose_name='MD5 Hash')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('pmd5', models.CharField(blank=True, default='', max_length=32, verbose_name='PMD5')),
                ('info_code', models.PositiveSmallIntegerField(default=0, verbose_name='Info Code')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Pages')),
                ('chars', models.PositiveIntegerField(default=0, verbose_name='Chars')),
            ],
            options={
                'verbose_name': 'Flibusta Book',
                'verbose_name_plural': 'Flibusta Books',
            },
        ),
        migrations.CreateModel(
            name='FlibustaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_code', models.CharField(max_length=45, unique=True, verbose_name='Genre Code')),
                ('genre_desc', models.CharField(blank=True, default='', max_length=99, verbose_name='Description')),
                ('genre_meta', models.CharField(blank=True, db_index=True, default='', max_length=45, verbose_name='Meta Genre')),
            ],
            options={
                'verbose_name': 'Flibusta Genre',
                'verbose_name_plural': 'Flibusta Genres',
            },
        ),
        migrations.CreateModel(
            name='FlibustaJoinedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Time')),
                ('bad_id', models.IntegerField(unique=True, verbose_name='Bad Book ID')),
                ('good_id', models.IntegerField(db_index=True, verbose_name='Good Book ID')),
                ('real_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Real ID')),
            ],
            options={
                'verbose_name': 'Flibusta Joined Book',
                'verbose_name_plural': 'Flibusta Joined Books',
            },
        ),
        migrations.CreateModel(
            name='FlibustaSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Sequence Name')),
            ],
            options={
                'verbose_name': 'Flibusta Sequence',
                'verbose_name_plural': 'Flibusta Sequences',
            },
        ),
        migrations.CreateModel(
            name='FlibustaBookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustaauthor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustabook')),
            ],
            options={
                'verbose_name': 'Flibusta Book-Author Link',
                'verbose_name_plural': 'Flibusta Book-Author Links',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='flibustabook',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='flibusta.FlibustaBookAuthor', to='flibusta.flibustaauthor', verbose_name='Authors'),
        ),
        migrations.CreateModel(
            name='FlibustaBookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustabook')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustagenre')),
            ],
            options={
                'verbose_name': 'Flibusta Book-Genre Link',
                'verbose_name_plural': 'Flibusta Book-Genre Links',
                'unique_together': {('book', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='flibustabook',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='flibusta.FlibustaBookGenre', to='flibusta.flibustagenre', verbose_name='Genres'),
        ),
        migrations.CreateModel(
            name='FlibustaBookSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_numb', models.IntegerField(default=0, verbose_name='Sequence Number')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Level')),
                ('type', models.PositiveSmallIntegerField(default=0, verbose_name='Type')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustabook')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flibusta.flibustasequence')),
            ],
            options={
                'verbose_name': 'Flibusta Book-Sequence Link',
                'verbose_name_plural': 'Flibusta Book-Sequence Links',
                'unique_together': {('book', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='flibustabook',
            name='sequences',
            field=models.ManyToManyField(related_name='books', through='flibusta.FlibustaBookSequence', to='flibusta.flibustasequence', verbose_name='Sequences'),
        ),
    ]
