# Generated by Django 6.0.3 on 2026-03-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flibusta', '0001_initial'),
        ('library', '0003_book_cover_book_file_bookserieslink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flibustabook',
            name='is_imported',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Imported'),
        ),
        migrations.CreateModel(
            name='FlibustaAuthorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flibusta_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='flibusta.flibustaauthor')),
                ('library_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flibusta_mapping', to='library.author')),
            ],
            options={
                'verbose_name': 'Flibusta Author Mapping',
                'verbose_name_plural': 'Flibusta Author Mappings',
            },
        ),
        migrations.CreateModel(
            name='FlibustaBookMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flibusta_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='flibusta.flibustabook')),
                ('library_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flibusta_mapping', to='library.book')),
            ],
            options={
                'verbose_name': 'Flibusta Book Mapping',
                'verbose_name_plural': 'Flibusta Book Mappings',
            },
        ),
        migrations.CreateModel(
            name='FlibustaGenreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flibusta_genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='flibusta.flibustagenre')),
                ('library_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flibusta_mapping', to='library.genre')),
            ],
            options={
                'verbose_name': 'Flibusta Genre Mapping',
                'verbose_name_plural': 'Flibusta Genre Mappings',
            },
        ),
        migrations.CreateModel(
            name='FlibustaSequenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flibusta_sequence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='flibusta.flibustasequence')),
                ('library_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flibusta_mapping', to='library.bookseries')),
            ],
            options={
                'verbose_name': 'Flibusta Sequence Mapping',
                'verbose_name_plural': 'Flibusta Sequence Mappings',
            },
        ),
    ]
