# Generated by Django 6.0.3 on 2026-03-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flibusta', '0002_flibustabook_is_imported_flibustaauthormapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flibustabook',
            name='is_imported',
        ),
    ]
